# -- Site Configuration --
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://coruscating-faun-9ad21b.netlify.app/"
defaultContentLanguage = "zh-cn"
disableLanguages = ["de", "en", "es", "fr", "it", "ja", "pt-br", "pt-pt"]

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = true

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = ""  # 域名审批后配置

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10
