locale = "zh-cn"
label = "简体中文"
weight = 1
title = "张津华丨Jasper Zhang"

[params]
  displayName = "张津华丨Jasper Zhang"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.svg"
  description = "个人学术主页 - PPE · 科研 · 思考"

[params.author]
  name = "张津华"
  email = "you@example.com"
  headline = ""
  bio = ""
  avatar = "img/avatar.svg"
  links = [
    { github = "https://github.com/hengdaoye50" },
  ]
