# -- Main Menu --
[[main]]
  name = "博客"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "作品集"
  pageRef = "portfolio"
  weight = 20

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 30

[[main]]
  name = "GitHub"
  url = "https://github.com/hengdaoye50"
  weight = 40

# -- Footer Menu --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "RSS 订阅"
  url = "/blog/index.xml"
  weight = 30
